# Generated by Django 3.1.7 on 2021-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pathLibro', models.FileField(upload_to='libros/')),
                ('titulo', models.CharField(max_length=30)),
                ('portada', models.FileField(upload_to='portadas/')),
                ('sinopsis', models.CharField(blank=True, max_length=1000)),
                ('formato', models.CharField(max_length=5)),
            ],
        ),
    ]
