# Generated by Django 3.1.7 on 2021-03-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('pathLibro', models.FileField(upload_to='libros/')),
                ('titulo', models.CharField(max_length=30)),
                ('portada', models.FileField(blank=True, upload_to='portadas/')),
                ('sinopsis', models.CharField(blank=True, max_length=1000)),
                ('formato', models.CharField(max_length=5)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libro.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Libro', models.ManyToManyField(blank=True, to='libro.Libro')),
            ],
        ),
    ]
