# Generated by Django 3.1.7 on 2021-03-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(default='Desconocido', on_delete=django.db.models.deletion.PROTECT, to='libro.autor'),
        ),
    ]
