# Generated by Django 3.1.7 on 2021-03-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20210329_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='libro.autor'),
        ),
    ]
