# Generated by Django 3.1.7 on 2021-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='Preferencias',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pathFoto',
            field=models.CharField(default='url de foto no especificada', max_length=150),
        ),
    ]
