# Generated by Django 3.1.7 on 2021-03-14 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210314_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='nickname',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='colorBg',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='colorLetra',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tipoLetra',
            field=models.CharField(default='arial', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
