# Generated by Django 3.1.7 on 2021-03-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210316_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='Preferencias',
        ),
    ]
