# Generated by Django 3.1.7 on 2021-03-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210309_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectorUsuario',
            new_name='Lector',
        ),
    ]
