# Generated by Django 3.1.7 on 2021-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210309_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='id',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nickname',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
