# Generated by Django 3.1.7 on 2021-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210318_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pathFoto',
            field=models.CharField(default='url de foto no especificada', max_length=150),
        ),
    ]
