# Generated by Django 3.1.7 on 2021-03-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20210309_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lector',
            new_name='Usuario',
        ),
    ]
